[package]
name = "mp_arena_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"

[dependencies.bevy]
version = "0.12.*"
default-features = true

[target.'cfg(not(target_family = "wasm"))'.dependencies.bevy]
version = "0.12.*"
default-features = true
features = ["dynamic_linking"]
